# YAML kba.pipeline config for generating clean_visible and then
## operating lingpipe

streamcorpus_pipeline:
  ## root path for all things that are called *_path in this file and
  ## are not an absolute path, i.e. start with '/'
  root_path: 

  ## pipeline expects strings over stdin, which are typically paths to
  ## streamcorpus.Chunk files.  They can also be some other kind of
  ## opaque byte strings delimited by newlines that your particular
  ## 'loader' is expecting.

  ## put logs inside each chunk file
  embedded_logs: true

  log_level: DEBUG

  output_chunk_max_count: 500

  ## the main pipeline log_dir_path can trigger similar log chunk
  log_dir_path: data/john-smith/

  ## tmp_dir_path, some extractors and loaders require this dir to be in
  ## the same file system as their output.  This is also where the
  ## batch_transforms operate.
  tmp_dir_path: tmp

  ## task_queue specifies the strings that are passed to an extractor
  ## to obtain a Chunk.  The strings might be paths in a file system
  ## or some other source of data.  The task_queue might simply be
  ## stdin, or it might be a more sophisticated shared queue.
  task_queue: stdin
  stdin:

  external_stages_path: src/examples/john_smith_custom_extractor.py

  ## generator of StreamItems
  extractor: john_smith_custom_extractor

  incremental_transforms: []

  batch_transforms: []

  loaders: [to_local_chunks]

  john_smith_custom_extractor:
    ## illustrate passing a path into a stage, see _john_smith.py comments
    ground_truth_path: data/john-smith/ground-truth.tsv

  to_local_chunks:
    #output_type: inplace
    output_type: otherdir
    output_path: data/john-smith/
    output_name: john-smith-from-external-stage-%(first)s

