
streamcorpus_pipeline:
  root_path: /home/ubuntu 

  embedded_logs: false

  log_level: INFO 

  output_chunk_max_count: 500

  tmp_dir_path:  tmp

  task_queue: registry
  registry:
    namespace: streamcorpus-2014-construct
    registry_addresses: ["redis.diffeo.com:2181"]
    registry_timeout: 120
    storage_addresses: ["prod-cassandra-1.diffeo.com:9160"]

  ## generator of StreamItems
  reader: from_s3_chunks

  incremental_transforms: [
    language, 
    guess_media_type, 
    clean_html, 
    hyperlink_labels, 
    clean_visible
    ]

  batch_transforms: []

  ## to_local_* must be last, because *moves* the tmp file away
  writers: [to_s3_chunks, to_local_tarballs]

  from_s3_chunks:
    aws_access_key_id_path:     keys/trec-aws-s3.aws_access_key_id
    aws_secret_access_key_path: keys/trec-aws-s3.aws_secret_access_key
    bucket: aws-publicdatasets
    s3_path_prefix: trec/kba/kba-streamcorpus-2013-v0_2_0
    tries: 10
    input_format: streamitem
    streamcorpus_version: v0_2_0
    gpg_decryption_key_path: keys/trec-kba-rsa.gpg-key.private

  to_s3_chunks:
    aws_access_key_id_path:     keys/trec-aws-s3.aws_access_key_id
    aws_secret_access_key_path: keys/trec-aws-s3.aws_secret_access_key
    bucket: aws-publicdatasets
    s3_path_prefix: trec/kba/kba-streamcorpus-2013-v0_3_0-clean_visible
    output_name: "%(date_hour)s/%(source)s-%(num)d-%(input_md5)s-%(md5)s"
    tries: 10
    gpg_decryption_key_path: keys/trec-kba-rsa.gpg-key.private
    gpg_encryption_key_path: keys/trec-kba-rsa.gpg-key.pub
    gpg_recipient: trec-kba
    verify_via_http: true
    cleanup_tmp_files: false  ## so to_local_tarballs can run below

  clean_html:
    included_language_codes: ["en", ""]

  hyperlink_labels:
    require_clean_html: true
    require_abs_url: true
    all_domains: true
    offset_types: [BYTES]

  clean_visible:
    require_clean_html: true

  to_local_tarballs:
    output_path: /data/trec-kba/data/streamcorpus-2014-v0_3_0-clean_visible-tarballs
    output_name: "%(date_hour)s/%(source)s-%(num)d-%(input_md5)s-%(md5)s"
