# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='src/protoStream.proto',
  package='protoStream',
  serialized_pb='\n\x15src/protoStream.proto\x12\x0bprotoStream\"0\n\x11\x41pplicationHeader\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\r\n\x05value\x18\x02 \x01(\t\"|\n\x11ProtoStreamHeader\x12\x0f\n\x07version\x18\x01 \x02(\t\x12\x1a\n\x12\x64\x65\x66\x61ult_entry_type\x18\x02 \x02(\t\x12:\n\x12\x61pplication_header\x18\x03 \x03(\x0b\x32\x1e.protoStream.ApplicationHeader\"\xa2\x01\n\x14ProtoStreamDelimiter\x12L\n\x0e\x64\x65limiter_type\x18\x01 \x01(\x0e\x32/.protoStream.ProtoStreamDelimiter.DelimiterType:\x03\x45ND\"<\n\rDelimiterType\x12\t\n\x05\x45NTRY\x10\x01\x12\x07\n\x03\x45ND\x10\x02\x12\t\n\x05INDEX\x10\x03\x12\x0c\n\x08\x43HECKSUM\x10\x04\"8\n\x13ProtoStreamChecksum\x12\x11\n\talgorithm\x18\x01 \x02(\t\x12\x0e\n\x06\x64igest\x18\x02 \x02(\tB\'\n\x18\x63om.spinn3r.api.protobufB\x0bProtoStream')



_PROTOSTREAMDELIMITER_DELIMITERTYPE = descriptor.EnumDescriptor(
  name='DelimiterType',
  full_name='protoStream.ProtoStreamDelimiter.DelimiterType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='ENTRY', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='END', index=1, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='INDEX', index=2, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='CHECKSUM', index=3, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=317,
  serialized_end=377,
)


_APPLICATIONHEADER = descriptor.Descriptor(
  name='ApplicationHeader',
  full_name='protoStream.ApplicationHeader',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='name', full_name='protoStream.ApplicationHeader.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='value', full_name='protoStream.ApplicationHeader.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=38,
  serialized_end=86,
)


_PROTOSTREAMHEADER = descriptor.Descriptor(
  name='ProtoStreamHeader',
  full_name='protoStream.ProtoStreamHeader',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='version', full_name='protoStream.ProtoStreamHeader.version', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='default_entry_type', full_name='protoStream.ProtoStreamHeader.default_entry_type', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='application_header', full_name='protoStream.ProtoStreamHeader.application_header', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=88,
  serialized_end=212,
)


_PROTOSTREAMDELIMITER = descriptor.Descriptor(
  name='ProtoStreamDelimiter',
  full_name='protoStream.ProtoStreamDelimiter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='delimiter_type', full_name='protoStream.ProtoStreamDelimiter.delimiter_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=2,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _PROTOSTREAMDELIMITER_DELIMITERTYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=215,
  serialized_end=377,
)


_PROTOSTREAMCHECKSUM = descriptor.Descriptor(
  name='ProtoStreamChecksum',
  full_name='protoStream.ProtoStreamChecksum',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='algorithm', full_name='protoStream.ProtoStreamChecksum.algorithm', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='digest', full_name='protoStream.ProtoStreamChecksum.digest', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=379,
  serialized_end=435,
)

_PROTOSTREAMHEADER.fields_by_name['application_header'].message_type = _APPLICATIONHEADER
_PROTOSTREAMDELIMITER.fields_by_name['delimiter_type'].enum_type = _PROTOSTREAMDELIMITER_DELIMITERTYPE
_PROTOSTREAMDELIMITER_DELIMITERTYPE.containing_type = _PROTOSTREAMDELIMITER;
DESCRIPTOR.message_types_by_name['ApplicationHeader'] = _APPLICATIONHEADER
DESCRIPTOR.message_types_by_name['ProtoStreamHeader'] = _PROTOSTREAMHEADER
DESCRIPTOR.message_types_by_name['ProtoStreamDelimiter'] = _PROTOSTREAMDELIMITER
DESCRIPTOR.message_types_by_name['ProtoStreamChecksum'] = _PROTOSTREAMCHECKSUM

class ApplicationHeader(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _APPLICATIONHEADER
  
  # @@protoc_insertion_point(class_scope:protoStream.ApplicationHeader)

class ProtoStreamHeader(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PROTOSTREAMHEADER
  
  # @@protoc_insertion_point(class_scope:protoStream.ProtoStreamHeader)

class ProtoStreamDelimiter(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PROTOSTREAMDELIMITER
  
  # @@protoc_insertion_point(class_scope:protoStream.ProtoStreamDelimiter)

class ProtoStreamChecksum(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PROTOSTREAMCHECKSUM
  
  # @@protoc_insertion_point(class_scope:protoStream.ProtoStreamChecksum)

# @@protoc_insertion_point(module_scope)
